let autoGeneratedOrderId = 1;
$('#txtOrderID').val('O-00' + autoGeneratedOrderId);

function loadAllOderDetails() {

    $("#orderTblBody").empty();

    for (let oDetails of orderDetails) {
        let orderRow = `<tr>
                        <td>${oDetails.iCode}</td>
                        <td>${oDetails.itemName}</td>
                        <td>${oDetails.price}</td>
                        <td>${oDetails.Qty}</td>
                        <td>${oDetails.total}</td>
                   </tr>`;
        $('#orderTblBody').append(orderRow);
        bool = false;
    }

}

function loadAllCustomersToCombo() {
    $('#orderCustomerID').empty();
    for (let customer of customerDB) {
        $("#orderCustomerID").append(`<option>${customer.id}</option>`)
    }
}


$('#orderCustomerID').on('click', function () {
    let customerID = $('#orderCustomerID').val();
    for (let i = 0; i < customerDB.length; i++) {
        if (customerDB[i].id === customerID) {
            $("#selectCusName").val(customerDB[i].name);
            $("#orderCustomerAddress").val(customerDB[i].address);
            $("#orderCustomerEmail").val(customerDB[i].email);
        }
    }
})

function loadAllItemToCombo() {
    $('#itemCodeCombo').empty();
    for (let item of ItemDB) {
        $("#itemCodeCombo").append(`<option>${item.code}</option>`)
    }
}

$('#itemCodeCombo').on('click', function () {
    let itemID = $('#itemCodeCombo').val();
    for (let i = 0; i < ItemDB.length; i++) {
        if (ItemDB[i].code === itemID) {
            $("#selectItemCode").val(ItemDB[i].code);
            $("#txtItemDescription").val(ItemDB[i].name);
            $("#txtItemPrice").val(ItemDB[i].price);
            $("#txtQTYOnHand").val(ItemDB[i].qty);
        }
    }
});

let bool = false;
let orderAmount = 0;
$('#btnAddToTable').on('click', function () {
    $("#orderTblBody").empty();
    loadAllOderDetails();

    let a = $("#txtItemPrice").val()
    let b = $('#txtQty').val()

    let tot = a * b;


    let orderArray = new Order(
        $("#selectItemCode").val(),
        $("#txtItemDescription").val(),
        $("#txtItemPrice").val(),
        $("#txtQty").val(),
        tot,
        $('#txtOrderID').val()
    );

    let qty1;
    let qty2;
    let tot1;
    let tot2;

    for (let i = 0; i < orderDetails.length; i++) {
        let test = orderDetails[i];

        if ($('#selectItemCode').val() === test.iCode && $('#txtOrderID').val() === test.orderId) {

            bool = true;
            qty1 = parseInt(test.Qty);
            tot1 = parseInt(test.total);
            qty2 = parseInt($("#txtQty").val());
            tot2 = parseInt(tot);

            test.iCode = $("#selectItemCode").val();
            test.itemName = $("#txtItemDescription").val();
            test.price = $("#txtItemPrice").val();
            test.Qty = (qty1 + qty2);
            test.total = (tot1 + tot2);

            $('#orderTblBody').empty();
        }
    }


    if (bool === false) {
        orderDetails.push(orderArray);
    }

    for (let i = 0; i < ItemDB.length; i++) {
        if (ItemDB[i].itemCode === $("#selectItemCode").val()) {
            ItemDB[i].qty = (ItemDB[i].qty) - ($("#txtQty").val());
        }
    }

    getAllItems();

    savedSuccessfully();

    loadAllOderDetails();

    $('#total').val()


    let x = $("#txtItemPrice").val()
    let y = $('#txtQty').val()

    let z = x * y;

    let singleOrder = new OrderDetails(
        $('#txtOrderID').val(),
        $('#txtDate').val(),
        $("#orderCustomerID").val(),
        $("#selectItemCode").val(),
        $("#txtQty").val(),
        z,
        $("#txtDiscount").val()
    );

    purchaseDetails.push(singleOrder);
    orderAmount += tot;
    loadAllPurchaseDetails();

});


let fullTot = 0;
let setTotZero = 0;
let fullAmount = 0;
$('#btnSubmitOrder').on('click', function () {

    let x = $("#txtItemPrice").val()
    let y = $('#txtQty').val()

    let z = x * y;


    let singleOrder = {
        oID: $('#txtOrderID').val(),
        date: $('#txtDate').val(),
        cID: $("#orderCustomerID").val(),
        iCode: $("#selectItemCode").val(),
        oQty: $("#txtQty").val(),
        Tot: z,
        discount: $("#txtDiscount").val()
    }

    purchaseDetails.push(singleOrder);

    clearTextField('#selectItemCode,#txtItemDescription,#txtItemPrice,#txtQTYOnHand');
    clearTextField('#orderCustomerID,#selectCusName,#orderCustomerContact,#orderCustomerAddress');

    savedSuccessfully();

    $('#txtOrderID').val('O-00' + autoGeneratedOrderId);
    autoGeneratedOrderId++;

    for (let i = 0; i < orderDetails.length; i++) {
        let totVal = orderDetails[i];
        fullTot += parseInt(totVal.total)
    }
    let disCount = parseInt($('#txtDiscount').val());// 10%

    let discountedPrice = ((orderAmount / 100) * disCount);//50


    let oAmount = parseInt(orderAmount);



    $('#total').val("Rs/= " + (oAmount - discountedPrice));

    let customCash = parseInt($('#txtCash').val());


    let subTotal = ((orderAmount/100) * disCount);
    $('#subtotal').val(subTotal)

    let s = customCash;

    let d = discountedPrice;

    let sbTot;

    if (discountedPrice > 0) {
        sbTot = subTotal;
        $('#subtotal').val(sbTot);
    } else {
        $('#subtotal').val("No discount");
    }

    let dc = s - d;

    $('#txtBalance').val(s - (oAmount - discountedPrice));




    $('#txtOrderID').val('O-00' + autoGeneratedOrderId);
    autoGeneratedOrderId++;

    orderAmount = 0;

    orderDetails.splice(0, orderDetails.length);
    loadAllOderDetails();
});



$('#btnClear').on('click', function () {
    clearTextField('#txtQty,#subtotal,#total');
    clearTextField('#txtCash,#txtDiscount,#txtBalance');
});


function clearTextField(txtFld) {
    $(txtFld).val('');
}
